# Generated by Django 5.2.7 on 2025-10-28 13:42

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=courses.models.handle_upload)),
                ('status', models.CharField(choices=[('pub', 'Publish'), ('soon', 'Coming soon'), ('draft', 'Draft')], default='draft', max_length=16)),
                ('access', models.CharField(choices=[('any', 'Anyone'), ('email_requred', 'Email required')], default='email_requred', max_length=16)),
            ],
        ),
    ]
