# Generated by Django 5.2.7 on 2025-11-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('publish', 'Published'), ('soon', 'Coming soon'), ('draft', 'Draft')], default='draft', max_length=16),
        ),
    ]
